elm-street-technology/elevate-ui

- src/Alert/index.js
- src/Button/index.js
- src/Datetime/index.js
- src/Input/index.js
- src/Label/index.js
- src/Paper/index.js
- src/Textarea/__snapshots__/Textarea.test.js.snap
- src/Textarea/index.js
- src/Typography/index.js
- src/Validation/index.js
Handles everything except the Toggle-related components
> Update passthrough props to account for withStyles HoC

- demo/src/docs/Textareas.js
textarea demo blows up on develop currently, because formik is somehow wired wrongly. Changed it to match the other demo files.
> fix textarea demo

- package.json
Sort of resolves https://github.com/elm-street-technology/elevate-ui/issues/31
> add deploy demo to deploy script

- demo/src/docs/Tables.js
- demo/src/layout/Sidebar.js
- src/Button/index.js
- src/Input/SearchInput.js
- src/Table/ActionButtons.js
- src/Table/CheckboxTable.js
- src/Table/FilterComponent.js
- src/Table/Pagination.js
- src/Table/index.js
> Table Updates

- src/Button/__snapshots__/Button.test.js.snap
- src/Button/index.js
Fixes the scroll issue where ripples on click wouldn't fire if the user has scrolled down the page. Also adjusts z-index issues that had been found when multi-select items dropdown over the button.
> Button Ripple Scroll Fix

- demo/public/docs/QueryForm.js
- demo/src/docs/QueryForm.js
- demo/src/layout/Main.js
- demo/src/layout/Sidebar.js
- src/MultiSelect/index.js
- src/Select/__snapshots__/Select.test.js.snap
- src/Select/index.js
This allows the `<Select />` and `<MultiSelect />` components to submit via a standard form submission (such as `myForm.submit()`)
> Hidden Inputs for Select and MultiSelect

- demo/public/docs/Hr.js
- demo/src/docs/Hr.js
- demo/src/layout/Main.js
- src/Hr/component.json
- src/Hr/index.js
- src/index.js
> Add simple Hr component

- demo/public/docs/Alert.js
- demo/public/docs/Button.js
- demo/src/docs/Alert.js
- demo/src/docs/Button.js
- src/Alert/Alert.test.js
- src/Alert/component.json
- src/Alert/index.js
- src/Button/component.json
- src/Button/index.js
> Update alert/button icon prop

- demo/src/docs/ButtonGroup.js
- src/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
- src/ButtonGroup/component.json
- src/ButtonGroup/index.js
- Also updates colors for span text based on bg color
- rewrites `onChange` handler a bit to remove `onClick`
> Bugfix for deselecting initial values

- demo/src/docs/Theme.js
Open to feedback on this, but just wanted to get all the options out there for reference.
> Add more documentation for Theme, close #108

- src/ButtonGroup/index.js
> Update ButtonGroup to match default input styles

- demo/src/docs/NumberIncrement.js
- demo/src/layout/Main.js
- demo/src/layout/Sidebar.js
- src/NumberIncrement/component.json
- src/NumberIncrement/index.js
Got this wrapped up and working well. Would love another set of eyes.
> Add NumberIncrement component

- demo/src/layout/Header.js
#hacktoberfest cleaning up my own mistakes 🎃
> Update menu icon for demo mobile nav

- demo/src/docs/CheckboxGroup.js
- demo/src/docs/RadioGroup.js
- src/Checkbox/component.json
- src/Checkbox/index.js
- src/CheckboxGroup/CheckboxGroup.test.js
- src/CheckboxGroup/component.json
- src/CheckboxGroup/index.js
- src/RadioGroup/RadioGroup.test.js
- src/RadioGroup/component.json
- src/RadioGroup/index.js
> Update CheckboxGroup and RadioGroup to take items prop instead of options

- demo/src/docs/Hr.js
- src/Hr/component.json
- src/Hr/index.js
> Add gutterBottom and gutterTop as default props, close #128

- demo/src/docs/Theme.js
- demo/src/layout/Header.js
- demo/src/layout/IconDoc.js
- demo/src/layout/Main.js
- src/Modal/index.js
- src/ThemeProvider/index.js
Will be a _breaking_ change: #127
> Update breakpoints from object to function

- demo/src/docs/Theme.js
- src/Button/index.js
- src/Modal/component.json
- src/Modal/index.js
- src/MultiSelect/index.js
- src/Select/index.js
- src/Table/index.js
- src/ThemeProvider/index.js
Looking for feedback on this. Usage example:
```js
const style = (theme) => ({
modal: {
zIndex: theme.zIndex['top']
},
mask: {
zIndex: theme.zIndex['midTop']
},
elementUnderMask: {
zIndex: theme.zIndex['mid']
},
evenLowerElement: {
zIndex: theme.zIndex['bottomMid']
},
lowestElement: {
zIndex: theme.zIndex['bottom'],
},
});
```
Inspired in part by how Material UI handles their `zIndex` values. (https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/zIndex.js)
> Add zIndex system, close #149

- demo/src/layout/Doc.js
- demo/src/layout/Main.js
- src/Modal/index.js
- src/MultiSelect/index.js
- src/Select/index.js
Fixes the background-color issue so the docs tables work properly on mobile and desktop.
> Fix responsive table styles in docs

- demo/src/docs/Theme.js
- demo/src/docs/Tooltip.js
- demo/src/layout/Main.js
- demo/src/layout/Sidebar.js
- src/ThemeProvider/index.js
- src/Tooltip/component.json
- src/Tooltip/index.js
Adds a tooltip component as mentioned in #140
> Tooltip Component

- demo/src/docs/ColorPicker.js
- demo/src/layout/Main.js
- demo/src/layout/Sidebar.js
- package.json
- src/ColorPicker/ColorPicker.test.js
- src/ColorPicker/__snapshots__/ColorPicker.test.js.snap
- src/ColorPicker/component.json
- src/ColorPicker/index.js
- yarn.lock
> Form Component: New Color Picker Component With HEX, RGB, RGBA Support

- src/NumberIncrement/index.js
> Fix NumberIncrement buttons in Edge

- demo/src/docs/Accordion.js
- src/Accordion/AccordionContents.js
Issue: https://github.com/elm-street-technology/elevate-ui/issues/172
> Render accordion children when open to prevent network requests

- src/ThemeProvider/index.js
Updated colors in Theme Provider to reflect those in the updated Brand Guidelines.
> Add dark and light variations to theme color palette

- src/Button/index.js
- src/Tooltip/component.json
- Clears timeout on button ripples to suppress memory leak errors
> Clear Button Ripple Timeout on Unmount

- demo/src/docs/Theme.js
Reverts elm-street-technology/elevate-ui#208
> Revert "Add dropdown zIndex"

- demo/src/docs/Theme.js
- src/Alert/index.js
- src/ThemeProvider/index.js
Added spacing to theme provider
```
const spacing = {
unit: 16,
};
```
> Added spacing to ThemeProvider

- demo/src/docs/Button.js
- src/Button/component.json
- src/Button/index.js
> Add transparent buttons

- CHANGELOG.md
- demo/src/docs/GlobalNotification.js
- demo/src/layout/Main.js
- demo/src/layout/Sidebar.js
- src/Alert/__snapshots__/Alert.test.js.snap
- src/Button/__snapshots__/Button.test.js.snap
- src/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
- src/Checkbox/__snapshots__/Checkbox.test.js.snap
- src/CheckboxGroup/__snapshots__/CheckboxGroup.test.js.snap
- src/ColorPicker/__snapshots__/ColorPicker.test.js.snap
- src/CurrencyInput/__snapshots__/CurrencyInput.test.js.snap
- src/Datetime/__snapshots__/Datetime.test.js.snap
- src/Feed/__snapshots__/Feed.test.js.snap
- src/GlobalNotification/Notification.js
- src/GlobalNotification/Notifications.js
- src/GlobalNotification/index.js
- src/Input/__snapshots__/Input.test.js.snap
- src/MultiSelect/__snapshots__/MultiSelect.test.js.snap
- src/RadioGroup/__snapshots__/RadioGroup.test.js.snap
- src/Select/__snapshots__/Select.test.js.snap
- src/Textarea/__snapshots__/Textarea.test.js.snap
- src/ThemeProvider/index.js
- src/Tooltip/__snapshots__/Tooltip.test.js.snap
- src/Typography/__snapshots__/Typography.test.js.snap
Adds the GlobalNotification functionality from our CRM application into Elevate UI.
https://github.com/elm-street-technology/elevate-ui/issues/220
> Add GlobalNotification functionality

- demo/src/docs/Typography.js
- demo/src/layout/PropsTable.js
- src/Feed/__snapshots__/Feed.test.js.snap
- src/Typography/Typography.test.js
- src/Typography/__snapshots__/Typography.test.js.snap
- src/Typography/index.js
> Add subHeading2 to Typography

- src/Table/CheckboxTable.js
- Adds the ability to pass callback props for Checkbox Table Selection Actions, so we can have more control over Actions management and display by passing the checkbox state to the parent
> Feature - Add Checkbox Table Selection Callbacks Props

- src/NumberIncrement/NumberIncrement.test.js
- src/NumberIncrement/__snapshots__/NumberIncrement.test.js.snap
- src/NumberIncrement/index.js
- Keeps default at 2 to avoid unexpected usage changes
- Unit test
Example - `places={0}`
> Adds Decimal Places Display Option for NumberIncrement Component

- .gitignore
Apply the pattern of removing lockfiles for dependencies to this project.
> Ignore Yarnlock
